# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pushkar Sheth
email: ph@sheth.cc
description: > # this means to ignore newlines until "baseurl:"
  Pushkar Sheth | Welcome | Writings on projects and research in mechanical engineering, coupled with electronics, programming and machine learning.
url: "https://ph.sheth.cc" # the base hostname & protocol for your site
github_username: phsheth    
scholar_username: eAIE2N4AAAAJ
address: WhiteField
#address2: Bengaluru
#address3: 3400 N. Charles St.
city: Bengaluru
state: Karnataka
zip: 560048 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

# Google Analytics
google_analytics: UA-124253635-1
